language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

install:
  - composer self-update
  - composer install

services:
  - elasticsearch

before_script:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.2.deb && sudo dpkg -i --force-confnew elasticsearch-1.5.2.deb
  - sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.5.0
  - sleep 10
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - sudo service elasticsearch restart
  
script: phpunit
